# Generated by Django 4.2 on 2023-05-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costdate',
            name='date_published',
        ),
        migrations.AlterField(
            model_name='costdate',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
