# Generated by Django 4.2 on 2023-05-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0002_remove_costdate_date_published_alter_costdate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='costdate',
            name='description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costitem',
            name='additional_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='costitem',
            name='units_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costitem',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costitem',
            name='unit_count',
            field=models.IntegerField(default=0),
        ),
    ]
