# Generated by Django 4.2 on 2023-05-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0003_costdate_description_costitem_additional_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costdate',
            old_name='date',
            new_name='costdate',
        ),
    ]
