# Generated by Django 4.2 on 2023-05-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0004_rename_date_costdate_costdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costdate',
            old_name='costdate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='costitem',
            old_name='date',
            new_name='costdate',
        ),
    ]
