# Generated by Django 4.2 on 2023-05-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0005_rename_costdate_costdate_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costitem',
            old_name='units_price',
            new_name='unit_price',
        ),
        migrations.AlterField(
            model_name='costdate',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
