# Generated by Django 4.2 on 2023-05-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0006_rename_units_price_costitem_unit_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costitem',
            old_name='costdate',
            new_name='cost_date',
        ),
        migrations.AlterField(
            model_name='costitem',
            name='unit_type',
            field=models.CharField(default='KG', max_length=25),
        ),
    ]
