# Generated by Django 4.2 on 2023-05-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0007_rename_costdate_costitem_cost_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costdate',
            name='date',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
