# Generated by Django 4.2 on 2023-05-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0009_alter_costdate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='costdate',
            name='day',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costdate',
            name='month',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costdate',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
