# Generated by Django 4.2 on 2023-05-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0010_costdate_day_costdate_month_costdate_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costdate',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costdate',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costdate',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
