# Generated by Django 4.2 on 2023-05-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0011_alter_costdate_day_alter_costdate_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costdate',
            name='read_only',
            field=models.BooleanField(default=False),
        ),
    ]
