# Generated by Django 4.2 on 2023-05-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0012_costdate_read_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutcomeItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('randemen_beras', models.FloatField(default=0)),
                ('berat_hasil_beras', models.IntegerField(default=0)),
                ('pemasukan', models.IntegerField(default=0)),
                ('keuntungan', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='CostDate',
            new_name='Date',
        ),
    ]
