# Generated by Django 4.2 on 2023-05-08 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0013_outcomeitems_rename_costdate_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Date',
            new_name='CostDate',
        ),
    ]
