# Generated by Django 4.2 on 2023-05-08 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0015_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
