# Generated by Django 4.2 on 2023-05-08 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0016_delete_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CostDate',
            new_name='Date',
        ),
    ]
