# Generated by Django 4.2 on 2023-05-08 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0018_rename_cost_date_costitem_the_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutcomeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('randemen_beras', models.FloatField(default=0)),
                ('berat_hasil_beras', models.IntegerField(default=0)),
                ('pemasukan', models.IntegerField(default=0)),
                ('keuntungan', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=1000)),
                ('the_date', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cost_calculator.date')),
            ],
        ),
        migrations.DeleteModel(
            name='OutcomeItems',
        ),
    ]
